version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3100:3306"
    volumes:
      - lemos_data:/var/lib/mysql

volumes:
  lemos_data: